### ISSUE TITLE
Création des (objets) ressources

### ISSUE THREAD

**Issue by Popcorns26** [ProgHunter/Seigneurie#4]
Créations des classes (et abstractions nécessaires) pour les premières ressources:
- [x] Bois
- [x] Nourriture
- [x] Minéraux
- [x] Population

S'assurer que le modèle est extensible pour ajouter d'autres ressources par la suite.
Le joueur commencera avec une petite quantité de chaque ressource de base.

**Comment by webmilio** [comment]
Est-ce qu'il est nécessaire d'avoir une/des classes pour ce type d'objets ? Un objet generique qui contient une référence vers un sprite/texture, un localization, etc. pourrais être une alternative.

**Comment by webmilio** [comment]
🥳🥳
